//! Faculty schemas: attribute IDs and kind markers per faculty.

pub mod archive;
pub mod atlas;
pub mod body;
pub mod cognition;
pub mod compass;
pub mod decide;
pub mod discord;
pub mod embeddings;
pub mod files;
pub mod gauge;
pub mod headspace;
pub mod mail;
pub mod memory;
pub mod message;
pub mod orient;
pub mod patience;
pub mod planner;
pub mod posture;
pub mod reason;
pub mod relations;
pub mod selfimage;
pub mod status;
pub mod teams;
pub mod triage;
pub mod voice;
pub mod web;
pub mod wiki;
